baseURL = "/"
languageCode = "es"
theme = "themes/wiston"
themesDir = ""
title = "Cuentos para no niños"
paginate = 6
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
google_analytics_id = ""
twitter_handle = "@alfonso_sr0"
showAuthorOnHomepage = true
showAuthorOnPosts = false
showIntroContentOnHomepage = true
showPostsOnHomepage = false
usePaginationOnHomepage = false
limitPostsOnHomepage = 3                                                                      # only used if usePaginationOnHomepage is false
sortPostsByDateOldestFirst = false
addDot = true
addFrame = true
highlightColor = '#7b16ff'
baseColor = "#ffffff"
baseOffsetColor = "#eaeaea"
headingColor = "#1c1b1d"
textColor = "#4e5157"
dotColor = "#7b16ff"
enableGoogleFonts = true
googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
fontFamilyHeading = "Poppins"
fontFamilyParagraph = "Helvetica"
fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[menu]
[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = "Cuentos"
identifier = "cuentos"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Quién soy"
identifier = "about"
weight = 3
url = "/about/"
#   [[menu.main]]
#     name = "Tags"
#     identifier = "tags"
#     weight = 4
#     url = "/tags/"
